# Save cache of dependencies
cache:
    paths:
    - vendor/

# Install dependencies
before_script:
    # Install git (the php image doesn't have it) which is required by composer
    - apt-get update -yqq
    - apt-get install git -yqq

    # Install composer
    - curl --silent --show-error https://getcomposer.org/installer | php

    # Install all project dependencies
    - php composer.phar install

    # Install and enable xdebug PHP extenstion
    - pecl install xdebug && docker-php-ext-enable xdebug

# PHP7.0 tests
test:7.0:
    image: php:7.0
    script:
        - vendor/bin/phpunit -v --bootstrap phpunit.php --configuration phpunit.xml --coverage-text --colors=never

# PHP7.1 tests
#test:7.1:
#    image: php:7.1
#    script:
#        - vendor/bin/phpunit -v --bootstrap phpunit.php --configuration phpunit.xml --coverage-text