# Project language
language: php

sudo: required

dist: trusty

# Language versions to test agains
php:
    - '7.0'
#    - '7.1'
#    - nightly
#    - hhvm

# Allow addons
addons:
    code_climate:
        repo_token: $CODECLIMATE_REPO_TOKEN

# Save cache of dependencies
cache:
    directories:
        - vendor/

# Install dependencies
install:
    - composer install

# Start tests
script:
    - vendor/bin/phpunit -v --bootstrap phpunit.php --configuration phpunit.xml --coverage-text --coverage-clover $TRAVIS_BUILD_DIR/build/logs/clover.xml --colors=never

# Submit coverage results
after_success:
    - vendor/bin/test-reporter -n --coverage-report=$TRAVIS_BUILD_DIR/build/logs/clover.xml --verbose